[package]
name = "weather-forecaster"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = {version="0.11.18", features = ["blocking", "json"]}
serde = {version ="1.0.174", features = ["derive"]}
tokio = { version = "1.0", features = ["full"] }
